name: Form Bot

on:
  schedule:

    # 平日10:00 JST
    - cron: '0 1 * * 1-5'

    # 平日13:00 JST
    - cron: '0 4 * * 1-5'

    # 平日16:00 JST
    - cron: '0 7 * * 1-5'

  workflow_dispatch:
# test

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:

      # =========================
      # リポジトリ取得
      # =========================
      - uses: actions/checkout@v4


      # =========================
      # Pythonセットアップ
      # =========================
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'


      # =========================
      # Chromeセットアップ
      # =========================
      - uses: browser-actions/setup-chrome@v1


      # =========================
      # 依存関係インストール
      # =========================
      - name: Install dependencies
        run: pip install -r requirements.txt


      # =========================
      # 実行
      # =========================
      - name: Run Form Bot
        env:
          EMPLOYEE_NUMBER: ${{ secrets.EMPLOYEE_NUMBER }}
          FORM_LAST_NAME: ${{ secrets.FORM_LAST_NAME }}
          FORM_FIRST_NAME: ${{ secrets.FORM_FIRST_NAME }}
          FORM_EMAIL: ${{ secrets.FORM_EMAIL }}
          OFFICE: ${{ secrets.OFFICE }}

        run: python main.py
