name: Form Bot

on:
  schedule:

    # 09:55 JST
    - cron: '55 0 * * 1-5'

    # 12:55 JST
    - cron: '55 3 * * 1-5'

    # 15:55 JST
    - cron: '55 6 * * 1-5'

  workflow_dispatch:


jobs:
  run:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Form Bot
        env:
          EMPLOYEE_NUMBER: ${{ secrets.EMPLOYEE_NUMBER }}
          FORM_LAST_NAME: ${{ secrets.FORM_LAST_NAME }}
          FORM_FIRST_NAME: ${{ secrets.FORM_FIRST_NAME }}
          FORM_EMAIL: ${{ secrets.FORM_EMAIL }}
          OFFICE: ${{ secrets.OFFICE }}

        run: python main.py
